### ISSUE TITLE
`pod trunk push` failed because of "An internal server error occurred"

### ISSUE THREAD

**Issue by NicholasTD07** [CocoaPods/trunk.cocoapods.org#207]
Related push logging:

```
** BUILD SUCCEEDED **

 -> TDRedux.swift (2.0.1)

opening connection to trunk.cocoapods.org:443...
opened
starting SSL for trunk.cocoapods.org:443...
SSL established
<- "POST /api/v1/pods?allow_warnings=false HTTP/1.1\r\nContent-Type: application/json; charset=utf-8\r\nAccept: application/json; charset=utf-8\r\nUser-Agent: CocoaPods/1.1.1\r\nAuthorization: Token <TOKEN>\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nHost: trunk.cocoapods.org\r\nContent-Length: 747\r\n\r\n"
<- "{\"name\":\"TDRedux.swift\",\"version\":\"2.0.1\",\"summary\":\"Yet another Redux written in Swift\",\"description\":\"TDRedux.swift is a micro framework which helps you build\\napps with the Redux architecture.\\nI wrote it because it is fun and easy to write your own Redux.\",\"homepage\":\"https://github.com/NicholasTD07/TDRedux.swift\",\"license\":{\"type\":\"MIT\",\"file\":\"LICENSE\"},\"authors\":{\"NicholasTD07\":\"Nicholas.TD07@gmail.com\"},\"social_media_url\":\"https://twitter.com/NicholasTD07\",\"module_name\":\"TDRedux\",\"platforms\":{\"ios\":\"8.0\",\"osx\":\"10.9\",\"watchos\":\"2.0\",\"tvos\":\"9.0\"},\"source\":{\"git\":\"https://github.com/NicholasTD07/TDRedux.swift.git\",\"tag\":\"2.0.1\"},\"source_files\":[\"Sources\",\"Sources/**/*.{h,m}\"],\"requires_arc\":true,\"pushed_with_swift_version\":\"3.0\"}\n"
-> "HTTP/1.1 500 Internal Server Error\r\n"
-> "Date: Fri, 18 Nov 2016 00:19:02 GMT\r\n"
-> "Connection: keep-alive\r\n"
-> "Strict-Transport-Security: max-age=31536000\r\n"
-> "Content-Type: application/json\r\n"
-> "Content-Length: 141\r\n"
-> "X-Content-Type-Options: nosniff\r\n"
-> "Server: thin 1.6.2 codename Doc Brown\r\n"
-> "Via: 1.1 vegur\r\n"
-> "\r\n"
reading 141 bytes...
-> "{\"error\":\"An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.\"}"
read 141 bytes
Conn keep-alive
[!] An internal server error occurred. Please check for any known status issues at https://twitter.com/CocoaPods and try again later.

/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk.rb:70:in `print_error'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk.rb:30:in `request_url'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk.rb:36:in `request_path'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:79:in `push_to_trunk'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.1.1/lib/pod/command/trunk/push.rb:65:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

Maybe related: https://cocoapods.org/pods/TDRedux.swift returning a page says `Internal Server Error` after I got the push error.

**Comment by segiddins** [comment]
I'm guessing https://github.com/CocoaPods/trunk.cocoapods.org/pull/205 somehow broke it, but I'm confused how

**Comment by NicholasTD07** [comment]
Thanks for the fast response. :)

Is there anything I can provide you to make you debug this easier?

A few things which might help:

**Repo**: https://github.com/NicholasTD07/TDRedux.swift

**How To Reproduce**:

- Clone the repo
- Try to push (if you send me your email, I can add you as an owner of the pod)

**Comment by NicholasTD07** [comment]
@segiddins ^ Forgot to at you

**Comment by mikeblanton** [comment]
I'm having the same problem trying to update https://cocoapods.org/pods/AffirmSDK... Searching on the web shows it's been updated to 2.2.0 (which is the version we're trying to push), but `pod search AffirmSDK` shows 2.1.1 as the latest. The podspec we're trying to push is at https://github.com/Affirm/affirm-ios-sdk/blob/master/AffirmSDK.podspec.

**Comment by ruddfawcett** [comment]
I am also having the same problem updating [Notepad](https://github.com/ruddfawcett/Notepad). Searching "Notepad" [shows the updated version](https://cocoapods.org/?q=notepad) (0.2.2). When I go to visit https://cocoapods.org/pods/Notepad I'm getting a 500 Internal Service error as well.

**Comment by segiddins** [comment]
I've disable pushes and am working on fixing things as we speak

**Comment by NicholasTD07** [comment]
@segiddins Thank you 👍

**Comment by segiddins** [comment]
Looks like it might be an issue with the GitHub API, that's the only conclusion I've been able to come to so far

**Comment by segiddins** [comment]
The following request to GitHub is failing:

```
HTTP put https://api.github.com/repos/CocoaPods/Specs/contents/Specs/b/f/e/SegiddinsTestPod/0.0.1/SegiddinsTestPod.podspec.json {:message=>"[Add] SegiddinsTestPod 0.0.1", :branch=>"master", :sha=>nil, :content=>"ewogICJuYW1lIjogIlNlZ2lkZGluc1Rlc3RQb2QiLAogICJ2ZXJzaW9uIjogIjAuMC4xIiwKICAic3VtbWFyeSI6ICJBIHBvZCB1c2VkIGZvciB0ZXN0aW5nIHB1c2hlZCB0byB0cnVuay4iLAogICJkZXNjcmlwdGlvbiI6ICJBIHVzZWxlc3MgcG9kIHVzZWQgb25seSB0byB0ZXN0IHB1c2hpbmcgbmV3IHNwZWNzIHRvIHRydW5rLiIsCiAgImhvbWVwYWdlIjogImh0dHBzOi8vZ2l0aHViLmNvbS9zZWdpZGRpbnMvU2VnaWRkaW5zVGVzdFBvZCIsCiAgImxpY2Vuc2UiOiAiTUlUIiwKICAiYXV0aG9ycyI6IHsKICAgICJTYW11ZWwgR2lkZGlucyI6ICJzZWdpZGRpbnNAc2VnaWRkaW5zLm1lIgogIH0sCiAgInNvdXJjZSI6IHsKICAgICJnaXQiOiAiaHR0cHM6Ly9naXRodWIuY29tL3NlZ2lkZGlucy9TZWdpZGRpbnNUZXN0UG9kLmdpdCIsCiAgICAidGFnIjogInJlbGVhc2UiCiAgfSwKICAic291cmNlX2ZpbGVzIjogImhlYWRlci5oIiwKICAicGxhdGZvcm1zIjogewogICAgIm9zeCI6IG51bGwsCiAgICAiaW9zIjogbnVsbCwKICAgICJ0dm9zIjogbnVsbCwKICAgICJ3YXRjaG9zIjogbnVsbAogIH0KfQo=", :author=>{:name=>"Samuel Giddins", :email=>"segiddins@segiddins.me"}, :committer=>{:name=>"CocoaPodsBot", :email=>"em@ail.com"}} 
=> 409 {"message":"refs/heads/master is at 8532b73b2869f30b7dfe0f26a4531554675ea723 but expected aa76817551c4a27fc4166757ac6c212134519394","documentation_url":"https://developer.github.com/v3/repos/contents/"}
```

**Comment by segiddins** [comment]
Fixed.
Turns out, a commit had succeeded and was in the git repo, but github's API didn't have it as the HEAD commit for master. I discovered this when I pulled the specs repo and discovered the head commit was  `8532b73b2869f30b7dfe0f26a4531554675ea723`, rather than the `aa76817551c4a27fc4166757ac6c212134519394` the gh web UI was showing. The issue was resolved by running `git pull && git checkout -b seg-branch && git push origin`. This caused the GitHub API / web UI / app servers to update their view of `master` and see the proper HEAD commit.

I've gone ahead and re-enabled pushes to trunk.

**Comment by segiddins** [comment]
@ MikeMcQuaid any chance you or someone at GitHub could shed some light on what happened here, and if there was something we should be doing to avoid this happening again? No rush since I managed to get the immediate issue resolved last night, just looking for some peace of mind. Thanks 🙌

**Comment by MikeMcQuaid** [comment]
@segiddins You're best to contact GitHub support for such things rather than CCing me (or any other employee) directly. Our support team will be able to help more than I will. Sorry and thanks!
