### ISSUE TITLE
The pod trunk info and pod trunk push failed because invalid JSON response

### ISSUE THREAD

**Issue by dreampiggy** [CocoaPods/trunk.cocoapods.org#444]
> pod trunk info SDWebImage

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/whoami/.gem/bin/pod trunk info SDWebImage
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.11.3
        Ruby : ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
    RubyGems : 3.0.3.1
        Host : macOS 12.6 (21G115)
       Xcode : 14.1 (14B47b)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 822107edaccc2af483f886b22799233d9d9d00cd

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Error

```
JSON::ParserError - 767: unexpected token at ''
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Users/whoami/.gem/ruby/2.6.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk.rb:103:in `json'
/Users/whoami/.gem/ruby/2.6.0/gems/cocoapods-trunk-1.6.0/lib/pod/command/trunk/info.rb:23:in `run'
/Users/whoami/.gem/ruby/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/whoami/.gem/bin/pod:23:in `load'
/Users/whoami/.gem/bin/pod:23:in `<main>'
```

**Comment by dreampiggy** [comment]
The server response seems is empty string `''`, which cause JSON decode failure

**Comment by dreampiggy** [comment]
Seems works now, effect 5 hours from May 17 12:30 GMT+8 to now
